---

- name: "awslogs | create directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/awslogs/state
    - /var/awslogs/etc

- name: "awslogs | configure awslogs agent"
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/etc/awslogs.conf
    owner: root
    group: root
    mode: 0644
  notify: restart awslogs

- name: "awslogs | configure awslogs credentials"
  template:
    src: aws.conf.j2
    dest: /var/awslogs/etc/aws.conf
