# NLM specifics for AWS Logs service
#   - Install a script and and service to pre-initalize AWS Logs
#   - Install some template files used by the service on startup
---

- name: "create NLM specific directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/awslogs/nlm
    - /var/awslogs/nlm/templates

- name: "install NLM specific pre-initialization script"
  copy:
    src: awslogs-reconfig
    dest: /var/awslogs/nlm/awslogs-reconfig
    mode: 0755

- name: "install NLM specific template for awslogs.conf"
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/nlm/templates/awslogs.conf.j2
    mode: 0644

- name: "install NLM specific pre-initalization service"
  copy:
    src: awslogs-init.service
    dest: /etc/systemd/system/awslogs-init.service
    mode: 0644

- name: "enable NLM specific pre-initialization service"
  service:
    name: awslogs-init.service
    enabled: yes
