# NLM specifics for AWS Logs service
#   - Install a script and and service to pre-initalize AWS Logs
#   - Install some template files used by the service on startup
---

- name: "create NLM specific directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/awslogs/nlm
    - /var/awslogs/nlm/lib
    - /var/awslogs/nlm/templates

- name: "install NLM requirements file"
  copy:
    src: "files/requirements.txt"
    dest: "/var/awslogs/nlm/requirements.txt"
    mode: 0644

- name: "Install additional packages"
  pip:
    executable: /var/awslogs/bin/pip
    requirements: /var/awslogs/nlm/requirements.txt
    state: present

- name: "install NLM python libraries"
  copy:
    src: "lib/{{ item }}"
    dest: "/var/awslogs/nlm/lib/{{ item }}"
    mode: 0644
  with_items:
    - nlminit.py

- name: "install NLM specific initialization script"
  copy:
    src: "bin/awslogs-reconfig.sh"
    dest: /var/awslogs/nlm/awslogs-reconfig.sh
    mode: 0755

- name: "install NLM specific template for aws.conf"
  copy:
    src: "templates/aws.conf.j2"
    dest: "/var/awslogs/nlm/templates/aws.conf.j2"
    mode: 0644

- name: "install NLM specific template for awslogs.conf"
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/nlm/templates/awslogs.conf.j2
    mode: 0644

- name: "install NLM specific initalization service"
  copy:
    src: awslogs-init.service
    dest: /etc/systemd/system/awslogs-init.service
    mode: 0644

- name: "enable NLM specific initialization service"
  service:
    name: awslogs-init.service
    enabled: yes
